# Generated by Django 3.2.8 on 2021-10-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram User ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('username', models.CharField(default='', max_length=100, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'botuser',
                'verbose_name_plural': 'botusers',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ManyToManyField(blank=True, to='record.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botuser.botuser', verbose_name='user history')),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'histories',
            },
        ),
    ]
