# Generated by Django 3.2.12 on 2022-09-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20211204_1637'),
        ('botuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='history',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='history',
            name='local',
            field=models.CharField(default='', max_length=100, verbose_name='Language'),
        ),
    ]
