# Generated by Django 3.2.8 on 2021-10-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='File Size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_id',
            field=models.CharField(default='', max_length=100, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='not-found.jpg', upload_to='resource_imgs', verbose_name='Image'),
        ),
    ]
