# Generated by Django 3.2.9 on 2021-11-14 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20211031_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, default='not-found.jpg', upload_to='resource_imgs', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(null=True, blank=True, verbose_name='Order'),
        ),
    ]
