# Generated by Django 3.2.9 on 2021-11-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20211114_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=1, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
