# Generated by Django 3.2.9 on 2021-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File Unique ID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Is Enabled?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File ID'),
        ),
    ]
