# Generated by Django 3.2.6 on 2021-09-11 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Last Name')),
                ('site', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Web Site')),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='Telegram User ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=70, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, default='', max_length=40, verbose_name='Username')),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Programming Language Name')),
                ('enabled', models.BooleanField(verbose_name='Is Enabled?')),
                ('order', models.IntegerField(verbose_name='Order')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Resource Name')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='About')),
                ('rating', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('enabled', models.BooleanField(default=False, verbose_name='Is Enabled?')),
                ('local', models.CharField(choices=[('TR', 'Turkish'), ('EN', 'English')], max_length=2, verbose_name='Language')),
                ('level', models.CharField(choices=[('BGN', 'Beginner'), ('EXP', 'Experinced'), ('PRO', 'Professional')], max_length=3, verbose_name='Level')),
                ('res_type', models.CharField(choices=[('BK', 'Book'), ('DC', 'Document'), ('LN', 'Link')], max_length=2, verbose_name='Type of Resource')),
                ('file_name', models.CharField(blank=True, max_length=100, verbose_name='File Name')),
                ('file_id', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='Website')),
                ('image', models.ImageField(blank=True, default='not-found.jpg', upload_to='resource_imgs', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='prodil_resource_related', related_query_name='prodil_resources', to='prodil.Author', verbose_name='Authors of Resource')),
                ('language', models.ManyToManyField(to='prodil.ProgrammingLanguage', verbose_name='Programming Language')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('res_type', 'DC')), fields=('file_name',), name='unique_document_file_name'),
        ),
    ]
