# Generated by Django 3.2.4 on 2021-08-18 11:28

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('site', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(blank=True, default='', max_length=70)),
                ('username', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=300, null=True)),
                ('rating', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('enabled', models.BooleanField(default=False)),
                ('local', models.CharField(choices=[('TR', 'Türkçe'), ('EN', 'English')], max_length=2)),
                ('level', multiselectfield.db.fields.MultiSelectField(choices=[('BGN', 'Başlangıç'), ('EXP', 'Orta'), ('PRO', 'Ileri')], max_length=11)),
                ('res_type', models.CharField(choices=[('BK', 'Kitap'), ('DC', 'Dokuman'), ('LN', 'Link')], max_length=2)),
                ('path', models.CharField(max_length=100, unique=True)),
                ('file_id', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(related_name='prodil_resource_related', related_query_name='prodil_resources', to='prodil.Author')),
                ('language', models.ManyToManyField(to='prodil.Category')),
            ],
        ),
    ]
