# Generated by Django 3.2.4 on 2021-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('res_type', 'DC')), fields=('path',), name='unique_document_path'),
        ),
    ]
