# Generated by Django 3.2.4 on 2021-08-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodil', '0002_auto_20210818_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BotUser',
        ),
        migrations.AlterField(
            model_name='resource',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
