# Generated by Django 3.2.4 on 2021-08-20 20:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prodil', '0003_auto_20210819_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='path',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='not-found.jpg', upload_to='<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BGN', 'Beginner'), ('EXP', 'Experinced'), ('PRO', 'Professional')], max_length=11),
        ),
        migrations.AlterField(
            model_name='resource',
            name='local',
            field=models.CharField(choices=[('TR', 'Turkish'), ('EN', 'English')], max_length=2),
        ),
        migrations.AlterField(
            model_name='resource',
            name='res_type',
            field=models.CharField(choices=[('BK', 'Book'), ('DC', 'Document'), ('LN', 'Link')], max_length=2),
        ),
    ]
