# Generated by Django 3.2.4 on 2021-08-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodil', '0004_auto_20210820_2002'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='unique_document_path',
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, default='not-found.jpg', upload_to='resource_imgs'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('res_type', 'DC')), fields=('file_name',), name='unique_document_file_name'),
        ),
    ]
